# Generated by Django 5.0.4 on 2024-05-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valyuta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valyuta', to='task.valyuta'),
            preserve_default=False,
        ),
    ]
