# Generated by Django 5.0.6 on 2024-05-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='valyuta',
            options={'verbose_name_plural': 'Valyutalar'},
        ),
    ]
